---
- name: Start Nextcloud
  block:
    - name: Create Nextcloud directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      with_items:
        - "{{ nextcloud_data_directory }}/nextcloud"
        - "{{ nextcloud_data_directory }}/mysql"
        - "{{ nextcloud_data_directory }}/redis"

    - name: Create Nextcloud network
      community.docker.docker_network:
        name: "{{ nextcloud_network_name }}"

    - name: Nextcloud Mariadb Docker Container
      community.docker.docker_container:
        name: "{{ nextcloud_db_container_name }}"
        image: "{{ nextcloud_db_image_name }}:{{ nextcloud_db_image_version }}"
        networks:
          - name: "{{ nextcloud_network_name }}"
        network_mode: "{{ nextcloud_network_name }}"
        pull: true
        volumes:
          - "{{ nextcloud_data_directory }}/mysql:/var/lib/mysql:rw"
        ports:
          - "3306:3306"
        env:
          MYSQL_DATABASE: "nextcloud"
          MYSQL_USER: "{{ nextcloud_sql_user }}"
          MYSQL_PASSWORD: "{{ nextcloud_sql_password }}"
          MYSQL_ROOT_PASSWORD: "{{ nextcloud_sql_root_password }}"
        restart_policy: unless-stopped
        memory: "{{ nextcloud_db_memory }}"

    - name: Nextcloud Redis Docker Container
      community.docker.docker_container:
        name: "{{ redis_container_name }}"
        image: "{{ redis_image_name }}:{{ redis_image_version }}"
        networks:
          - name: "{{ nextcloud_network_name }}"
        network_mode: "{{ nextcloud_network_name }}"
        pull: true
        volumes:
          - "{{ nextcloud_data_directory }}/redis:/data:rw"
        restart_policy: unless-stopped
        memory: "{{ redis_memory }}"

    - name: Nextcloud Docker Container
      community.docker.docker_container:
        name: "{{ nextcloud_container_name }}"
        image: "{{ nextcloud_image_name }}:{{ nextcloud_image_version }}"
        networks:
          - name: "{{ nextcloud_network_name }}"
        network_mode: "{{ nextcloud_network_name }}"
        pull: true
        volumes:
          - "{{ nextcloud_data_directory }}/nextcloud:/var/www/html:rw"
        ports:
          - "{{ nextcloud_port }}:80"
        env:
          PUID: "{{ nextcloud_user_id }}"
          PGID: "{{ nextcloud_group_id }}"
          MYSQL_HOST: "{{ nextcloud_db_container_name }}"
          MYSQL_DATABASE: "nextcloud"
          MYSQL_USER: "{{ nextcloud_sql_user }}"
          MYSQL_PASSWORD: "{{ nextcloud_sql_password }}"
          REDIS_HOST: "{{ nextcloud_container_name }}"
          REDIS_HOST_PORT: "6379"
          NEXTCLOUD_TRUSTED_DOMAINS: "{{ nextcloud_hostname }}.{{ ansible_nas_domain }} 192.168.0.8"
        restart_policy: unless-stopped
        memory: "{{ nextcloud_memory }}"
        labels:
          traefik.enable: "{{ nextcloud_available_externally | string }}"
          traefik.http.routers.nextcloud.rule: "Host(`{{ nextcloud_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.nextcloud.tls.certresolver: "letsencrypt"
          traefik.http.routers.nextcloud.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.nextcloud.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.nextcloud.loadbalancer.server.port: "80"
          homepage.group: Media
          homepage.name: Nextcloud
          homepage.icon: nextcloud.png
          homepage.href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ nextcloud_port }}"
          homepage.description: Open source dropbox alternative
          homepage.widget.type: nextcloud
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ nextcloud_port }}"
  when: nextcloud_enabled is true

- name: Stop Nextcloud
  block:
    - name: Stop Nextcloud
      community.docker.docker_container:
        name: "{{ nextcloud_container_name }}"
        state: absent
    - name: Stop Nextcloud DB
      community.docker.docker_container:
        name: "{{ nextcloud_db_container_name }}"
        state: absent
    - name: Stop Nextcloud Redis
      community.docker.docker_container:
        name: "{{ redis_container_name }}"
        state: absent
  when: nextcloud_enabled is false
