---
- name: Start Gitea
  block:
    - name: Create Gitea Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        recurse: true
      loop:
        - "{{ code_root }}/gitea"
        - "{{ gitea_data_directory }}/gitea"
        - "{{ gitea_data_directory }}/mysql"

    - name: Create MySQL container for Gitea
      community.docker.docker_container:
        name: "{{ gitea_mysql_container_name }}"
        image: "{{ gitea_mysql_image_name }}:{{ gitea_mysql_image_version }}"
        pull: true
        volumes:
          - "{{ gitea_data_directory }}/mysql:/var/lib/mysql:rw"
        env:
          MYSQL_DATABASE: "gitea"
          MYSQL_USER: "gitea"
          MYSQL_PASSWORD: "gitea"
          MYSQL_ROOT_PASSWORD: "gitea"
        restart_policy: unless-stopped
        memory: "{{ gitea_mysql_memory }}"

    - name: Create Gitea container
      community.docker.docker_container:
        name: "{{ gitea_container_name }}"
        image: "{{ gitea_image_name }}:{{ gitea_image_version }}"
        pull: true
        volumes:
          - "{{ code_root }}/gitea:/data:rw"
          - "{{ gitea_data_directory }}/gitea:/data/log:rw"
        ports:
          - "{{ gitea_port_http }}:3000"
          - "{{ gitea_port_ssh }}:22"
        links:
          - "{{ gitea_mysql_container_name }}:db"

        env:
          # Gitea
          GITEA__server__DOMAIN: "{{ gitea_hostname }}.{{ ansible_nas_domain }}"
          GITEA__server__ROOT_URL: "https://{{ gitea_hostname }}.{{ ansible_nas_domain }}/"
          GITEA__server__SSH_DOMAIN: "{{ gitea_ssh_hostname }}.{{ ansible_nas_domain }}"
          GITEA__server__SSH_PORT: "{{ gitea_port_ssh }}"

          # Database
          GITEA__database__DB_TYPE: "mysql"
          GITEA__database__HOST: "db:3306"
          GITEA__database__NAME: "gitea"
          GITEA__database__USER: "gitea"
          GITEA__database__PASSWD: "gitea"

          # Runtime
          GITEA__server__RUN_MODE: "prod"
          USER_UID: "1000"
          USER_GID: "1000"
        restart_policy: unless-stopped
        memory: "{{ gitea_memory }}"
        labels:
          traefik.enable: "{{ gitea_available_externally | string }}"

          traefik.http.routers.gitea.rule: >-
            Host(`{{ gitea_hostname }}.{{ ansible_nas_domain }}`)

          traefik.http.routers.gitea.tls: "true"
          traefik.http.routers.gitea.tls.certresolver: "letsencrypt"
          traefik.http.routers.gitea.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.gitea.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.gitea.loadbalancer.server.port: "3000"
  when: gitea_enabled | bool

- name: Stop Gitea
  block:
    - name: Stop Gitea
      community.docker.docker_container:
        name: "{{ gitea_container_name }}"
        state: absent

    - name: Stop Gitea MySQL
      community.docker.docker_container:
        name: "{{ gitea_mysql_container_name }}"
        state: absent
  when: gitea_enabled is false
