---
##    ________               _          _   _____   _____
##   / ____/ /_  ____ _____ ( )_____   / | / /   | / ___/
##  / /   / __ \/ __ `/ __ \|// ___/  /  |/ / /| | \__ \
## / /___/ / / / /_/ / /_/ / (__  )  / /|  / ___ |___/ /
## \____/_/ /_/\__,_/\____/ /____/  /_/ |_/_/  |_/____/
##  Chao's NAS https://github.com/leonhartyao/ansible_yao

# Add your all.yml config overrides to this file. See group_vars/all.yml for all possible settings.

# Example options
ansible_nas_hostname: nas
ansible_nas_timezone: Europe/Berlin
ansible_nas_user: chao
ansible_nas_email: chao@yaohaha.net
ansible_nas_domain: yaohaha.net
ansible_python_interpreter: /usr/bin/python3
cloudflare_type: "A"
samba_shares_root: /mnt/disk1
code_root: "{{ samba_shares_root }}/repos"
samba_server_string: Chao's NAS

# WARNING: Weird things might happen if you share the same data over Samba and NFS and allow writes on both!
nfs_shares_root: /mnt/disk1

nfs_exports:
  - "{{ nfs_shares_root }}/public *(rw,sync,no_root_squash)"


# The account used when Samba shares are accessed. Shouldn't need to change this unless you want to
# mess with Samba user permissions.
samba_guest_account: ansible-nas

## Enable some applications
bazarr_enabled: true
bitwarden_enabled: false
bitwarden_admin_token: fHO9TnuCBqqI7eUEkZpu0P4m3D/kiyHxyg+qG64WuXLNj8Co5+wuWbqluHoDnRva
bitwarden_allow_signups: false
cloudflare_ddns_enabled: true
cloudflare_token: "7YFBx0A_mTMZVfjuRmXq3zIKK0g_Jshz_Kksc1yJ"
deluge_enabled: true
glances_enabled: true
healthchecks_enabled: true
healthchecks_url: "https://hc-ping.com/73e93789-8c8a-4b35-979c-ad02005954fe"
heimdall_enabled: true
heimdall_port_http: "37211"
heimdall_available_externally: true
homeassistant_enabled: true
jackett_enabled: true
jellyfin_enabled: true
lidarr_enabled: true
navidrome_enabled: true
navidrome_available_externally: true
nextcloud_enabled: true
nextcloud_available_externally: true
plex_enabled: true
portainer_enabled: true
radarr_enabled: true
sonarr_enabled: true
# speedtest_tracker_enabled: true
traefik_enabled: true
watchtower_enabled: true
# youtubedlmaterial_enabled: true
# youtubedlmaterial_available_externally: true
